Added more birthday splashes
MCPI-Revival/MCPIL pull request #50
Opened 2021-04-03 00:49 UTC by leha-code

2021-04-03 01:15 UTC, TheBrokenRail commented on src/mcpil.py
> +        if not time_now.day == 1 and not time_now.month == 4: #The month and the day isn't the Aprils's fools day
This is in another PR.

2021-04-03 01:15 UTC, TheBrokenRail commented on src/mcpil.py
> +        splash = "BED.HEAL(\"TheBoyLeastLikelyTo\");"
Who is this? What is the criteria for who is added here? Because we can't add everyone.

2021-04-03 02:11 UTC, nobody5050 requested changes
this is mostly a useless pr.

2021-04-03 13:49 UTC, leha-code commented
I added least likel and gamercat

2021-04-03 13:50 UTC, leha-code commented
They asked for it

2021-04-03 13:51 UTC, leha-code commented
Ill change ths evening everything that is needed

2021-04-03 13:52 UTC, leha-code commented
I wont add anyone else
That. Was the last. Sorry typing froman ebook is hell

2021-04-27 18:39 UTC, StealthHydra179 commented
1. Inactive 2. Requested changes not made 3. PR not needed

2021-04-27 18:39 UTC, closed without merging